/*
 * Copyright (c) 2022 Yosapat.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Yosapat - initial API and implementation and/or initial documentation
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author Yosapat
 */
public class FormMainMenu extends JFrame {

    /**
     * Creates new form FormMainMenu
     */
    public FormMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUser = new javax.swing.JMenu();
        jMenuItemLogOff = new javax.swing.JMenuItem();
        jMenuStore = new javax.swing.JMenu();
        jMenuItemBuyMusic = new javax.swing.JMenuItem();
        jMenuItemHistory = new javax.swing.JMenuItem();
        jMenuManage = new javax.swing.JMenu();
        jMenuIManageMusic = new javax.swing.JMenuItem();
        jMenuIManageMusicGenre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.darkGray);
        setPreferredSize(new java.awt.Dimension(1080, 720));

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));

        jDesktopPane1.setBackground(java.awt.Color.darkGray);
        jDesktopPane1.setOpaque(false);
        jDesktopPane1.setLayout(new javax.swing.BoxLayout(jDesktopPane1, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        jMenuUser.setText("User");

        jMenuItemLogOff.setText("Log Off");
        jMenuUser.add(jMenuItemLogOff);

        jMenuBar1.add(jMenuUser);

        jMenuStore.setText("Store");

        jMenuItemBuyMusic.setText("Buy Music");
        jMenuStore.add(jMenuItemBuyMusic);

        jMenuItemHistory.setText("History");
        jMenuStore.add(jMenuItemHistory);

        jMenuBar1.add(jMenuStore);

        jMenuManage.setText("Manage");

        jMenuIManageMusic.setText("Manage Music");
        jMenuManage.add(jMenuIManageMusic);

        jMenuIManageMusicGenre.setText("Manage Music Genre");
        jMenuManage.add(jMenuIManageMusicGenre);

        jMenuBar1.add(jMenuManage);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormMainMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuIManageMusic;
    private javax.swing.JMenuItem jMenuIManageMusicGenre;
    private javax.swing.JMenuItem jMenuItemBuyMusic;
    private javax.swing.JMenuItem jMenuItemHistory;
    private javax.swing.JMenuItem jMenuItemLogOff;
    private javax.swing.JMenu jMenuManage;
    private javax.swing.JMenu jMenuStore;
    private javax.swing.JMenu jMenuUser;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JMenuItem getjMenuIManageMusic() {
        return jMenuIManageMusic;
    }

    public javax.swing.JMenuItem getjMenuIManageMusicGenre() {
        return jMenuIManageMusicGenre;
    }

    public javax.swing.JMenuItem getjMenuItemBuyMusic() {
        return jMenuItemBuyMusic;
    }

    public javax.swing.JMenuItem getjMenuItemHistory() {
        return jMenuItemHistory;
    }

    public javax.swing.JMenuItem getjMenuItemLogOff() {
        return jMenuItemLogOff;
    }

    public javax.swing.JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    public javax.swing.JMenu getjMenuManage() {
        return jMenuManage;
    }

    public javax.swing.JMenu getjMenuStore() {
        return jMenuStore;
    }
}
